baseURL = "http://soehlert.com/"
languageCode = "en-us"
title = "Sam Oehlert"
theme = "m10c"

[author]
  name = "Sam Oehlert"
  description = "Infosec engineer with way too many hobbies"

[[params.social]]
  name = "github"
  url = "https://github.com/soehlert"

