baseURL = "https://soehlert.com/"
languageCode = "en-us"
title = "Sam Oehlert"
theme = "m10c"

[params]
  author = "Sam Oehlert"
  description = "Infosec engineer with way too many hobbies"
  GitHubUser = "soehlert"

  [[params.social]]
    name = "github"
    url = "https://github.com/soehlert"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/samoehlert"

  [[params.social]]
    name = "instagram"
    url = "https://www.instagram.com/samoehlert/"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/samoehlert"

  [params.style]
    # Sidebar
    darkestColor = "#314c59"
    # Background
    darkColor = "#253031"
    # Purple
    primaryColor = "#800080"
    # Description
    lightColor = "#808080"
    # Title
    lightestColor = "#fff"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about"

  [[menu.main]]
    identifier = "posts"
    name = "blog"
    url = "/posts/"

  [[ menu.main ]]
    identifier = "music"
    name = "music"
    url = "https://soundcloud.com/soehlert"

[imaging]
  resampleFilter = "box"
  quality = 75
  anchor = "smart"
